---
title: Scratch coördinaten
hero_image: images / banner.png
description: Meer informatie over coördinaten in Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Scratch coördinaten
