---
title: Skrape koordinater
hero_image: images / banner.png
description: Lær om koordinater i Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "ripe"
steps:
  - 
    title: Skrape koordinater
