---
title: Scratch-Koordinaten
hero_image: Bilder / Banner.png
description: Erfahren Sie mehr über Koordinaten in Scratch
original_url: ""
theme: cc-Prototyp
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "kratzen"
steps:
  - 
    title: Scratch-Koordinaten
