---
title: Krapkoördinate
hero_image: beelde / banner.png
description: Leer oor koördinate in Scratch
original_url:
theme: cc-prototipe
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "krap"
steps:
  - 
    title: Krapkoördinate
