---
title: Tọa độ đầu
hero_image: images / banner.png
description: Tìm hiểu về các tọa độ trong Scratch
original_url:
theme: nguyên mẫu cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "vết trầy"
steps:
  - 
    title: Tọa độ đầu
