---
title: Coordinate Scratch
hero_image: images / banner.png
description: Scopri le coordinate in Scratch
original_url: ""
theme: cc-prototipo
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "graffiare"
steps:
  - 
    title: Coordinate Scratch
