---
title: Coordenadas do Scratch
hero_image: images/banner.png
description: Aprende acerca de coordenadas no Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Coordenadas do Scratch
