---
title: Coordenadas de rascunho
hero_image: images / banner.png
description: Saiba mais sobre coordenadas no Scratch
original_url:
theme: protótipo cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "coçar, arranhão"
steps:
  - 
    title: Coordenadas de rascunho
