---
title: Koordinate u Scratchu
hero_image: images/banner.png
description: Saznaj više o koordinatama u Scratchu
original_url: ""
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Koordinate u Scratchu
