---
title: Raaputuskoordinaatit
hero_image: Kuvien / banner.png
description: Opi koordinaateista tyhjästä
original_url:
theme: CC-prototyyppi
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "naarmu"
steps:
  - 
    title: Raaputuskoordinaatit
