---
title: Scratch koordinaatit
hero_image: images/banner.png
description: Opi koordinaateista Scratchissa
original_url:
theme: cc-prototyyppi
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Scratch koordinaatit
