---
title: Gwasgwch gyfesurynnau
hero_image: delweddau / banner.png
description: Dysgwch am gydlynu yn Scratch
original_url:
theme: cc-prototeip
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "crafu"
steps:
  - 
    title: Gwasgwch gyfesurynnau
