---
title: Coordenadas Scratch
hero_image: images / banner.png
description: Aprende sobre las coordenadas en Scratch
original_url: ""
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "rasguño"
steps:
  - 
    title: Coordenadas Scratch
