---
title: Koordinat gores
hero_image: gambar / banner.png
description: Pelajari tentang koordinat di Scratch
original_url: ""
theme: cc-prototipe
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "menggaruk"
steps:
  - 
    title: Koordinat gores
