---
title: Koordinate praske
hero_image: images / banner.png
description: Več o koordinatah v Scratchu
original_url:
theme: cc-prototip
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "praska"
steps:
  - 
    title: Koordinate praske
