---
title: Scratch koordináták
hero_image: images/banner.png
description: Ismerd meg a koordinátákat a Scratchben
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Scratch koordináták
