---
title: Karcázási koordináták
hero_image: images / banner.png
description: Ismerje meg a koordinátákat a Scratchban
original_url:
theme: cc-prototípus
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "karcolás"
steps:
  - 
    title: Karcázási koordináták
