---
title: 划痕坐標
hero_image: 圖片/ banner.png
description: 在Scratch中了解坐標
original_url: ""
theme: CC-原型
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "刮"
steps:
  - 
    title: 划痕坐標
