---
title: Współrzędne w Scratchu
hero_image: images/banner.png
description: Dowiedz się więcej o współrzędnych w Scratchu
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Współrzędne w Scratchu
