---
title: Współrzędne Scratch
hero_image: images / banner.png
description: Dowiedz się więcej o współrzędnych w Scratch
original_url: ""
theme: prototyp cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "zadraśnięcie"
steps:
  - 
    title: Współrzędne Scratch
