---
title: Scratch súradnice
hero_image: images / banner.png
description: Získajte viac informácií o súradniciach v aplikácii Scratch
original_url:
theme: cc-prototyp
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "škrabanec"
steps:
  - 
    title: Scratch súradnice
