---
title: Skrapkoordinater
hero_image: images / banner.png
description: Lär dig om koordinater i Scratch
original_url:
theme: cc-prototyp
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "repa"
steps:
  - 
    title: Skrapkoordinater
