---
title: Koordinat Scratch
hero_image: imej / banner.png
description: Ketahui mengenai koordinat dalam Scratch
original_url:
theme: prototaip cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "awal"
steps:
  - 
    title: Koordinat Scratch
