---
title: Koordinate u Scratch-u
hero_image: images/banner.png
description: Saznaj o koordinatama u Scratch-u
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Koordinate u Scratch-u
