---
title: Les coordonnées dans Scratch
hero_image: images/banner.png
description: En savoir plus sur les coordonnées dans Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Les coordonnées dans Scratch
