---
title: Scratch koordinatları
hero_image: images / banner.png
description: Scratch'deki koordinatlar hakkında bilgi edinin
original_url:
theme: cc-prototip
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "çizik"
steps:
  - 
    title: Scratch koordinatları
